manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Terence-1
      url-base: https://github.com/Terence-1
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-usb-reporting
      remote: Terence-1
      revision: main
  self:
    path: config
